### PR TITLE
KUZBO-21 gitter integration

### PR DESCRIPTION
**Pull request by j33f**
Added a link to the gitter chat to the menu

Zombie seems to not like the gitter "sidecar" widget script

### CODE REVIEW

**Comment by xbill82** [comment]
Yo! I like the menu item and the icon, but this is the kind of things that I'd rather put at the bottom of the sidebar. Like, it's not really "business", it's more a "support-y" thing.
Maybe, in the mid-term we could have a small button-group at the bottom of the sidebar with the links to GitHub issues, Gitter, email... Some kind of "all the way to report problems or ask features" grouped in one place.

What do you think?

**Comment by j33f** [comment]
yup, just forgot the style... hum...

**Comment by j33f** [comment]
done (+ issues links)

**Comment by xbill82** [comment]
:+1:

**Pull request merged**
